_target_: jaxmapp.roadmap.learned_sampler.CTRMSampler

inference_fn: 
params: 
num_samples: 50
num_rw_samples: 15
max_T: 64
rw_type: "uniform"
prob_rw_decay_high: 25.0
prob_rw_decay_low: 5.0
prob_rw_after_goal: 1.0
num_rw_attempts: 3 
max_speed_discount: 0.99