[build-system]
requires = ["setuptools", "wheel", "cython"]
build-backend = 'setuptools.build_meta'

[tool.pysen]
version = "0.10.1"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
py_version = "py39"

[[tool.pysen.lint.mypy_targets]]
paths = ["."]